# Generated by Django 3.0.3 on 2020-02-12 13:20

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('articles', '0002_article_is_draft'),
    ]

    operations = [
        migrations.AlterField(
            model_name='article',
            name='is_draft',
            field=models.BooleanField(default=True),
        ),
        migrations.AlterField(
            model_name='article',
            name='title',
            field=models.CharField(default='Noob', max_length=50),
        ),
    ]
